#!/usr/bin/env bash

if
  [[ -s "/home/olya/.rvm/gems/ruby-2.5.0@global/environment" ]]
then
  source "/home/olya/.rvm/gems/ruby-2.5.0@global/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/olya/.rvm/gems/ruby-2.5.0@global/environment'" >&2
  exit 1
fi
